### PR TITLE
Add support for Redis' requirepass option (password auth).

### PR DESCRIPTION
**Pull request by Eihrister**
Hello!

For our setup, we would like to use Redis' password authentication as an extra layer of security.
Since this is a trivial change, I took the liberty to implement it for us, and then create this pull request.

Daniël

### CODE REVIEW

**Comment by GUI** [comment]
Fantastic, thanks!

I'll try to get this published as a new luarock release sometime this week.

**Comment by GUI** [comment]
This is now part of the v0.9.0 release that's published now. Thanks again for your contribution!

**Comment by edeis53** [comment]
@Eihrister are you using auth along with TransitEncryptionEnabled? eg. ssl connection?

**Comment by jordanade** [comment]
> @Eihrister are you using auth along with TransitEncryptionEnabled? eg. ssl connection?

Does lua-resty-auto-ssl support TransitEncryptionEnabled?

**Pull request merged**
