### PR TITLE
update dehydrated to 0.6.5

### LINKED ISSUE #189: missing ACMEv2 support: account creation / new domains will stop working soon
> Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.

### PR DESCRIPTION
**Pull request by luto**
fixes #189

### CODE REVIEW

**Comment by luto** [comment]
Currently breaks:
> + Generating account key...
> + Registering account key with ACME server...
> + Fetching account ID...
> err: /usr/bin/resty-auto-ssl/letsencrypt_hooks: line 75: > this_hookscript_is_broken__dehydrated_is_working_fine__please_ignore_unknown_hooks_in_your_script: command not found

**Comment by luto** [comment]
CI fails, but [has been failing for a while](https://circleci.com/gh/GUI/lua-resty-auto-ssl/tree/master) :/ this works on my machine(TM), @GUI can you please take a look?

**Comment by aviatrix** [comment]
@luto this seems like a flaky test judging by the nightly build history, if you re-run it couple of times it might work ..

**Comment by GUI** [comment]
Thanks! This is now released in v0.13.0 that's out.

And sorry for the confusion about the test suite. That's been a bit of a nagging issues for a while, but I've hopefully improved the reliability of some of the flaky tests as part of https://github.com/GUI/lua-resty-auto-ssl/pull/193.

**Pull request merged**
