### PR TITLE
Allow users to configure which db of redis to use

### PR DESCRIPTION
**Pull request by RainFlying**

### CODE REVIEW

**Comment by GUI** [comment]
@RainFlying: Sorry for the very belated response! I've been busy with other work, but I think this looks useful, so I'll try to take a closer look and get this released sometime in the next couple weeks.

**Comment by luto** [comment]
@RainFlying sidenote: there are [tests for all the current redis options](https://github.com/GUI/lua-resty-auto-ssl/blob/master/t/redis.t). If you got a spare minute, adding one for this new one would be great. Feel free to copy/paste the [prefix test](https://github.com/GUI/lua-resty-auto-ssl/blob/master/t/redis.t#L292) - it should contain all the parts you need to test this one.

**Comment by luto** [comment]
In addition to the test, a quick note in the documentation (README.md) would be great, so people can use this without reading the code.

**Comment by GUI** [comment]
I added a test for this in https://github.com/GUI/lua-resty-auto-ssl/commit/181c9b30a88b32252eae311e6556bcb8f4b3fad1

@RainFlying: Thanks for the PR! This is now part of the v0.12.0 release.

**Pull request merged**
