### PR TITLE
Add support for setting redis key prefix.

### PR DESCRIPTION
**Pull request by brettg**
This PR adds support for a Redis key prefix set via a `prefix` config option. 

I'm relatively new to Lua, let me know if I can help with style changes or the like. I was able to test on a running server (with and without the prefix set) but unfortunately have not yet been able to get an environment correctly setup to run the tests.

### CODE REVIEW

**Comment by brettg** [comment]
With a couple changes to the `Makefile` I was able to get the tests running and passing (on Ubuntu at least, my macOS homebrew luarocks install is using an unexpected directory structure that includes the Lua version, `t/vendor/lib/luarocks/rocks-5.2/...`). 

That change doesn't explain the first CircleCI build failure, but master had an intermittent and similar looking failure around the same time...

**Comment by GUI** [comment]
Apologies for the belated response, but thanks for the pull request and for adding tests! I'll try to take a closer look at this in the next few days and get it merged and released (I'd also like to get some of the upstream letsencrypt.sh changes in at the same time). Much appreciated!

**Comment by brettg** [comment]
Before I actually hadn't added a test, just confirmed that they still passed. But, I've added one now.

Thanks for taking a look!

**Comment by GUI** [comment]
Thanks, and looks great! This is now part of the v0.10.0 release.

**Pull request merged**
